strangerstudios/pmpro-payfast

classes/class.pmprogateway_payfast.php
Cancel subscription when user cancels their account.
=> Cancel Subscription Code

services/payfast_itn_handler.php
This fixes a recurring subscription check.
Check function 'Amount In Cart'
=> Recurring Subscriptions Fix

classes/class.pmprogateway_payfast.php
Remove daily/weekly options as PayFast does not support this.
=> remove daily/weekly

readme.txt
Update readme to include sandbox details.
=> Update readme to include sandbox details

services/payfast_itn_handler.php
New orders weren't being created when a user recurring subscription went off.
=> Bug Fix: New orders weren't creating

classes/class.pmprogateway_payfast.php
Cancel the user's membership level when cancelled in PayFast.
=> Cancel process for PayFast

classes/class.pmprogateway_payfast.php, pmpro-payfast.php, services/payfast_itn_handler.php
No thinking here, just phpcbf doing its magic on saving file
=> wpcs first pass

languages/pmpro-payfast_POT.pot, pmpro-payfast.php, services/payfast_itn_handler.php
WordPress coding standards updates:
* prefixed functions with pmpro_payfast
* Added i18n support
* sanitize all $_POST types in the ITN handler.
=> WPCS updates

classes/class.pmprogateway_payfast.php, services/payfast_itn_handler.php
BUG FIX: Removed commented out code.
ENHANCEMENT: Switch over to use http api instead of cURL.
=> Remove CURL and use WP_REMOTE_POST

classes/class.pmprogateway_payfast.php, services/payfast_itn_handler.php
Sanitize incoming post params using pmpro_getParam
=> Sanitize incoming POST params better.

services/payfast_itn_handler.php
=> Prefix ITN handler constants.

pmpro-payfast.php, readme.txt
Update readme and version to .8.2
=> Update readme and version

pmpro-payfast.php, readme.txt
=> Update master to lastest version 0.8.3

classes/class.pmprogateway_payfast.php, pmpro-payfast.php
Bug Fix: Fixed issue where billing page update was causing a 500 error. This now redirects to PayFast.
=> Bug Fix: Billing page update button fatal error

pmpro-payfast.php, readme.txt
=> Version bump and changelog

classes/class.pmprogateway_payfast.php, pmpro-payfast.php, readme.txt, services/payfast_itn_handler.php
=> Update master to 0.8.4

pmpro-payfast.php
=> Fixes fatal error when PMPro Core is inactive

pmpro-payfast.php
=> PHP Notices fixed when creating/editing levels

classes/class.pmprogateway_payfast.php
Related to #64
@andrewlimaza  Fixed this, I've just tested on my side. Can confirm it works now as expected when following the steps mentioned in the issue.
=> Fixes order amount when using a discount code

classes/class.pmprogateway_payfast.php
Moved the pmpro_payfast_data filter further down.
Added the $order variable to the pmpro_payfast_data  filter
=> pmpro_payfast_data Filter moved  further down

classes/class.pmprogateway_payfast.php, services/payfast_itn_handler.php
This PR aims to:
- fix some 18n minor issues
- clean some unused code
- fix some undefined variables (typos, old code, ...)
- remove duplicate code
=> Fix docblock, unused, undefined

services/payfast_itn_handler.php
Adds MMPU compatibility for plugin.
=> Only cancel relevent level on subscription cancellation

classes/class.pmprogateway_payfast.php, pmpro-payfast.php, services/payfast_itn_handler.php
Replaces all references of getOption to get_option throughout the plugin.
=> Updates getOption to get_option

classes/class.pmprogateway_payfast.php
* ENHANCEMENT: Moved over to using the newer `pmpro_calculate_profile_start_date`
=> Fix profile start date issue
